version: '3'
services:
    web:
        build: .
        working_dir: /root
        volumes:
          -  ./:/root
        command: sh -c "npm install && npm run dev"
        # command: sh -c "npm run build && npm start"
        ports:
          - 3001:3001
          - 9229:9229 # chrome debugger port

        environment:
          NODE_ENV: testing
          PORT: 3001
          HOST: '0.0.0.0'
        depends_on:
          - db
    db:
        image: postgree
        ports:
        - "3306:3306"

        # test environment
        environment:
           POSTGRES_PASSWORD: secretrootpass89327843
           POSTGRES_USER: riotusr
           POSTGRES_DB: riot

    adminer:
        image: adminer
        ports:
            - 8080:8080